language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest test/test.py
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=SuperEncryptedSecret