language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify?secret=SuperEncryptedSecret
  email:
    - nagov-mark@mail.ru