N_FOR_NGRAMS_DEFAULT = 2
WITH_PUNC_DEFAULT = False
COUNT_AVG_DEFAULT = False
TOP_N_WORDS_DEFAULT = None  # None if you want to remember all words

MAX_LEN_OF_PARTS_TO_ANALYSE_IN_COUNT_AVG = 1000
ANALYSE_FRAGMENTS_DENSITY = 1  # > 0
